import type { Perfume, Brand } from '@/types'

export const MOCK_BRANDS: Brand[] = [
  { id: '1', name: 'Dior', slug: 'dior', created_at: '' },
  { id: '2', name: 'Chanel', slug: 'chanel', created_at: '' },
  { id: '3', name: 'Tom Ford', slug: 'tom-ford', created_at: '' },
  { id: '4', name: 'YSL', slug: 'ysl', created_at: '' },
  { id: '5', name: 'Lancôme', slug: 'lancome', created_at: '' },
]

export const MOCK_PERFUMES: (Perfume & { brand: Brand })[] = [
  {
    id: '1',
    name: 'Sauvage',
    slug: 'sauvage',
    brand_id: '1',
    brand: MOCK_BRANDS[0],
    volume: '100ml',
    description: 'Uma fragrância selvagem e nobre ao mesmo tempo. Notas de bergamota da Calábria, pimenta Sichuan e ambroxan criam uma composição moderna e intensa.',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f'],
    featured: true,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
  {
    id: '2',
    name: 'Bleu de Chanel',
    slug: 'bleu-de-chanel',
    brand_id: '2',
    brand: MOCK_BRANDS[1],
    volume: '100ml',
    description: 'Uma fragrância lenhosa e aromática que celebra a liberdade. Notas de citrus, incenso, cedro e sândalo criam uma assinatura única e sofisticada.',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683702'],
    featured: true,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
  {
    id: '3',
    name: 'Black Orchid',
    slug: 'black-orchid',
    brand_id: '3',
    brand: MOCK_BRANDS[2],
    volume: '50ml',
    description: 'Uma fragrância floral e oriental luxuosa. Notas de trufa preta, ylang ylang, bergamota e sândalo criam uma composição misteriosa e sedutora.',
    images: ['https://images.unsplash.com/photo-1587017539504-67cfbddac569'],
    featured: true,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
  {
    id: '4',
    name: 'Libre',
    slug: 'libre',
    brand_id: '4',
    brand: MOCK_BRANDS[3],
    volume: '90ml',
    description: 'Uma fragrância floral e amaderada que representa a liberdade feminina. Lavanda marroquina, flor de laranjeira e baunilha em perfeita harmonia.',
    images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f'],
    featured: false,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
  {
    id: '5',
    name: 'La Vie Est Belle',
    slug: 'la-vie-est-belle',
    brand_id: '5',
    brand: MOCK_BRANDS[4],
    volume: '75ml',
    description: 'A vida é bela. Iris, pralinê, patchouli e baunilha compõem este ícone da perfumaria moderna, evocando alegria e feminilidade.',
    images: ['https://images.unsplash.com/photo-1608181831688-8b8d90b64e95'],
    featured: false,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
  {
    id: '6',
    name: 'Fahrenheit',
    slug: 'fahrenheit',
    brand_id: '1',
    brand: MOCK_BRANDS[0],
    volume: '100ml',
    description: 'Audacioso e único. Violeta, cedro, couro e notas balsâmicas criam uma fragrância que desafia convenções e define uma era.',
    images: ['https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc'],
    featured: false,
    price: null,
    installments: null,
    created_at: '',
    updated_at: '',
  },
]
